<!--Section Titulo-->		
<div class="container ">
	<div class="row bg-dark bg-gradient mt-1 rounded">
					
		<div class="col-md-12 mt-3 mb-5 ">
		
			<h1 class=" display-6 text-center text text-white">
				Squad 
				<span class="text-warning">Poker</span>
			</h1>
						
		</div>
					
	</div>
</div>

<div class="container mt-4 mb-5 ">
    <h4  class="border-bottom " >Selecione uma pontuação abaixo </h4>
    <div class="row d-flex justify-content-center">
        <div id="pontos" class="mt-5">  
        </div>
    </div>

<?php
    
	require_once "app/view/app/usuarios.phtml";
	require_once "app/view/app/modal.phtml";
?>	
