<!---Menu Superior-->
<div class="menuSup">
	<!--Barra de Navegacao superior-->
	<nav class="navbar navbar-expand-md navbar-light p-0">
		
		<div id='abrirMenu' class="btn-Sup">
				<i class="text-warning fas fa-gamepad"></i>
		</div>
		<!-- Logo -->
		<a href="" class="navbar-brand">
			<h4 class="text text-white">Squad <span class="text-warning">Poker</span></h4> 
		</a>

		<div class="container">
			<div class="collapse navbar-collapse">
				<ul class="navbar-nav ml-auto ">
					<li class="nav-item">
						<div class="nav-link text-warning  mr-2">  
							<span class="text-center p-5">Bem Vindo</span>
							<span class="text-info text-align">
							<?php
							 echo trim($_SESSION['cNome'])
							 ?>
							 </span>
						</div>					
					</li>
					<li class="nav-item dropdown">
						<a href="" class="nav-link dropdown-toggle text-white" 
						data-toggle="dropdown">Desconectar</a>
						<div class="dropdown-menu">
							<a href="/Poker/sair" class="dropdown-item">Sair</a>	
						</div>
					</li>
				</ul>
			</div>
		</div>
	</nav>

</div>
<!--Secao
---------------------------------------------------->
<section id='conteudoHome' class="bg-light">
  <?= $this->reqView() ?>
  

<!--Footer
 --------------------------------------------------->
 <footer class="mt-5 mb-4 ">
   <!--Container Footer-->
   <div class="container ">
     <!--Linha Row-->
     <div class="row border-top">
   
       <div class="col-md-12 d-flex justify-content-center mt-4">
         <a href="https://github.com/EduardoParo" class="btn btn-outline-dark ml-2  text-white bg-success">
           <i class="fab fa-github"></i>
		   github.com/EduardoParo
         </a>
       </div>
       
     </div><!--Fim da Row Linha-->
   </div><!--Fim Cointainer-->   
</footer>
  	
</section>