<!-- Section MODAL
      ----------------------------------------------------------->  
        <!-- Modal -->
        <div class="modal fade" id="telaModal" tabindex="       -1" role="dialog" aria-labelledby="             exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <!--Container-->
                <div class="modal-content">
                    <header>
                        <div id="titulo_modal_div" class="modal-header text-warning">
                            <h5 class="modal-title" id="titulo_modal">TITULO MODAL</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    </header>
                    <!--Seção Formulario nesses casos a Row vem depois do Formulario
                    ----------------------------------------------------------------------------------------->
                    
                    <div id="conteudo_modal" class="modal-body">

                            
                    </div>

                    <div class="modal-footer">
                    <button type="button" id="btn_sim_modal" 		    class="btn btn-secondary bg-warning" 		data-dismiss="modal">Sim</button>	
      		        <button type="button" id="btn_voltar_modal" 		class="btn btn-secondary" 		data-dismiss="modal">Voltar</button>	
      		      </div>

      		    </div>
      		</div>
        </div>